### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by shreyaslad** [KingPixil/NewMe#4]
@KingPixil,

Here is an idea that I think will help your personal website...
## Smoothscroll

I have this great Jquery snippet that will slightly enhance your smoothscroll

Right Now, your smoothscroll is kinda instant. It's sort of like HTML smoothscrol, however it doesn't give your clients the understanding of where they are on the page.

Courtesy of [ABeautifulSite](https://www.abeautifulsite.net/smoothly-scroll-to-an-element-without-a-jquery-plugin-2), this jquery smoothscroll snippet will help your clients

`$('a[href^="#"]').on('click', function(event) {
    var target = $(this.getAttribute('href'));
    if( target.length ) {
        event.preventDefault();
        $('html, body').stop().animate({
            scrollTop: target.offset().top
        }, 1000);
    }
});`

**Comment by kbrsh** [comment]
Hey @NightStalkers 

Thanks for the PR, but I already have smooth scroll :confused:

I also don't ever want to use JQuery, ever. I prefer vanilla javascript any day, it's faster, and lets me learn more about the language.

Tip: If you want to format code which spans multiple lines, use three backticks (```), put your code in the second line, and close with three more backticks.
